# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=255, blank=True)),
                ('direccion', models.CharField(max_length=255, blank=True)),
                ('barrio', models.CharField(max_length=255, blank=True)),
                ('localidad', models.CharField(max_length=255, blank=True)),
                ('provincia', models.CharField(max_length=255, blank=True)),
                ('pais', models.CharField(max_length=255, blank=True)),
                ('modelo', models.IntegerField(null=True, blank=True)),
                ('entidad', models.CharField(max_length=255, blank=True)),
                ('ramo', models.CharField(max_length=255, blank=True)),
                ('cant_acciones', models.CharField(max_length=255, blank=True)),
                ('fecha_desde', models.DateField(null=True, blank=True)),
                ('destino', models.CharField(max_length=255, blank=True)),
                ('origen', models.CharField(max_length=255, blank=True)),
                ('superficie', models.DecimalField(help_text='Superficie de la propiedad', null=True, max_digits=10, decimal_places=2, blank=True)),
                ('unidad_medida_id', models.IntegerField(blank=True, help_text='Unidad de medida usada para la superficie', null=True, choices=[(0, 'm2'), (1, 'ha')])),
                ('m_mejoras_id', models.IntegerField(blank=True, null=True, choices=[(0, '$'), (1, 'us$'), (2, 'E'), (3, '$ Uruguayos'), (4, '\xa3'), (5, 'A'), (6, 'A$'), (7, '$L')])),
                ('mejoras', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('m_valor_fiscal_id', models.IntegerField(blank=True, null=True, choices=[(0, '$'), (1, 'us$'), (2, 'E'), (3, '$ Uruguayos'), (4, '\xa3'), (5, 'A'), (6, 'A$'), (7, '$L')])),
                ('valor_fiscal', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('m_valor_adq_id', models.IntegerField(blank=True, null=True, choices=[(0, '$'), (1, 'us$'), (2, 'E'), (3, '$ Uruguayos'), (4, '\xa3'), (5, 'A'), (6, 'A$'), (7, '$L')])),
                ('valor_adq', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('fecha_hasta', models.DateField(null=True, blank=True)),
                ('titular_dominio', models.CharField(max_length=255, blank=True)),
                ('porcentaje', models.DecimalField(help_text="<strong>NO</strong> incluir el signo '%'.<br> Si ingresa un n\xfamero decimal use '.' (punto) como delimitador", null=True, max_digits=10, decimal_places=2, blank=True)),
                ('vinculo', models.CharField(default='Titular', help_text='Indica la relacion con el titular de la DDJJ', max_length=255, blank=True, choices=[('Conviviente', 'Conviviente'), ('C\xf3nyuge', 'C\xf3nyuge'), ('Hijo/a', 'Hijo/a'), ('Titular', 'Titular')])),
                ('periodo', models.CharField(max_length=255, blank=True)),
                ('obs', models.CharField(max_length=255, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_bien_s', models.CharField(max_length=255, blank=True)),
                ('nombre_bien_s', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['tipo_bien', 'nombre_bien'],
                'db_table': 'biens',
                'verbose_name_plural': 'bienes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('jurisdiccion', models.CharField(max_length=255, blank=True)),
                ('cargo', models.CharField(help_text='Nombre del cargo', max_length=255)),
                ('poder_id', models.IntegerField(blank=True, null=True, choices=[(0, 'Ejecutivo'), (1, 'Legislativo'), (2, 'Judicial')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cargo'],
                'db_table': 'cargos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ContenidoDdjjs',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('ddjj_id', models.IntegerField(null=True, blank=True)),
                ('ddjj_ano', models.CharField(max_length=255, blank=True)),
                ('ddjj_tipo', models.CharField(max_length=255, blank=True)),
                ('poder_id', models.IntegerField(null=True, blank=True)),
                ('persona_str', models.CharField(max_length=255, blank=True)),
                ('persona_id', models.IntegerField(null=True, blank=True)),
                ('cargo_str', models.CharField(max_length=255, blank=True)),
                ('cargo_id', models.IntegerField(null=True, blank=True)),
                ('contenido', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contenido_ddjjs',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ddjj',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ano', models.IntegerField()),
                ('tipo_ddjj_id', models.IntegerField(choices=[(0, 'alta'), (1, 'baja'), (2, 'inicial'), (3, 'anual')])),
                ('funcionario', models.CharField(help_text='Este campo lo completa el sistema.', max_length=255, blank=True)),
                ('url', models.CharField(help_text='Url DocumentCloud', max_length=255, blank=True)),
                ('key', models.IntegerField(help_text='Este campo lo completa el sistema.', null=True, blank=True)),
                ('clave', models.CharField(help_text='Este campo lo completa el sistema.', max_length=255, blank=True)),
                ('flag_presenta', models.IntegerField(default=1, choices=[(0, 'Si'), (1, 'No')], blank=True, help_text="<strong style='color:blue'>'Solo el PDF'</strong> si solo se muestra el pdf, ej: cartas donde declaran que la ddjj es igual a la del a\xf1o anterior", null=True, verbose_name='Carta de DDJJ')),
                ('obs', models.TextField(blank=True)),
                ('flag_search', models.CharField(help_text='Este campo lo completa el sistema.', max_length=255, blank=True)),
                ('visitas', models.DecimalField(null=True, max_digits=10, decimal_places=0, blank=True)),
                ('status', models.IntegerField(default=0, help_text='Indica si puede ser publicada', choices=[(0, 'Deshabilitado'), (1, 'Habilitado')])),
                ('poder_id', models.IntegerField(choices=[(0, 'Ejecutivo'), (1, 'Legislativo'), (2, 'Judicial')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['persona'],
                'db_table': 'ddjjs',
                'verbose_name': 'Declaraci\xf3n Jurada',
                'verbose_name_plural': 'Declaraciones Juradas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=255)),
                ('poder_id', models.IntegerField(blank=True, null=True, choices=[(0, 'Ejecutivo'), (1, 'Legislativo'), (2, 'Judicial')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'jurisdiccions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NombreBien',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=255, blank=True)),
                ('tipo_bien_id', models.IntegerField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'nombre_biens',
                'verbose_name_plural': 'Nombre Bienes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('legajo', models.CharField(max_length=255, blank=True)),
                ('tipo_documento_id', models.IntegerField(blank=True, null=True, choices=[(0, 'dni'), (1, 'le'), (2, 'lc'), (3, 'pasaporte')])),
                ('documento', models.IntegerField(null=True, blank=True)),
                ('cuit_cuil', models.CharField(max_length=255, blank=True)),
                ('nacimento', models.DateField(null=True, blank=True)),
                ('sexo_id', models.IntegerField(blank=True, null=True, choices=[(0, 'M'), (1, 'F')])),
                ('estado_civil_id', models.IntegerField(blank=True, null=True, choices=[(0, 'Casado/a'), (1, 'C\xf3nyugue'), (2, 'Divorciado/a'), (3, 'Separado'), (4, 'Soltero/a'), (5, 'U. Hecho'), (6, 'Viudo/a')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_id', models.CharField(help_text='ID del tag en el diario La Naci\xf3n', max_length=255, blank=True)),
                ('tag_img_id', models.CharField(help_text='ID de la img del tag', max_length=255, blank=True)),
                ('tag_descripcion', models.CharField(help_text='Descripcion del tag Nacion', max_length=255, blank=True)),
                ('ficha_d_l', models.CharField(help_text='Url ficha de Directorio Legislativo', max_length=255, blank=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
                'db_table': 'personas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PersonaCargo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('flag_ingreso', models.IntegerField(null=True, blank=True)),
                ('ingreso', models.DateField(null=True, blank=True)),
                ('egreso', models.DateField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(to='admin_ddjj_app.Cargo')),
                ('jurisdiccion', models.ForeignKey(blank=True, to='admin_ddjj_app.Jurisdiccion', null=True)),
                ('persona', models.ForeignKey(to='admin_ddjj_app.Persona')),
            ],
            options={
                'ordering': ['cargo'],
                'db_table': 'persona_cargos',
                'verbose_name_plural': 'Persona Cargos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TiempoControls',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('dias', models.CharField(max_length=255, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tiempo_controls',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoBien',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=255, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'tipo_biens',
                'verbose_name_plural': 'Tipo Bienes',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='ddjj',
            name='persona',
            field=models.ForeignKey(related_name='ddjjs', to='admin_ddjj_app.Persona'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ddjj',
            name='persona_cargo',
            field=models.ForeignKey(related_name='ddjjs', to='admin_ddjj_app.PersonaCargo', help_text='Indique el cargo que ocupa para esta DDJJ'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cargo',
            name='personas',
            field=models.ManyToManyField(to='admin_ddjj_app.Persona', through='admin_ddjj_app.PersonaCargo'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bien',
            name='ddjj',
            field=models.ForeignKey(related_name='bienes', to='admin_ddjj_app.Ddjj', help_text='Indica la DDJJ a la cual pertenece este bien'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_bien',
            field=models.ForeignKey(related_name='bienes', to='admin_ddjj_app.NombreBien'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bien',
            name='persona',
            field=models.ForeignKey(help_text='Es el titular del bien, este puede ser distinto al titular de la DDJJ', to='admin_ddjj_app.Persona'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bien',
            name='tipo_bien',
            field=models.ForeignKey(related_name='bienes', to='admin_ddjj_app.TipoBien'),
            preserve_default=True,
        ),
    ]
